export const packingList = [
  { id: 1, name: 'The complete TravelWiser packing list' },
  { id: 2, name: 'My veru own beautiful packing list' },
  { id: 3, name: "Adam's list" },
  { id: 4, name: 'Made for Asia' },
];

export const categories = [
  {
    id: 1,
    category: 'Clothes',
    items: [
      { id: 10, name: 'socks', amount: 12 },
      { id: 11, name: 'underwear', amount: 15 },
      { id: 12, name: 'undershirts/bras', amount: 0 },
      { id: 13, name: 't-shirt', amount: 0 },
      { id: 14, name: 'pants', amount: 0 },
      { id: 15, name: 'socks', amount: 0 },
      { id: 16, name: 'underwear', amount: 0 },
      { id: 17, name: 'undershirts/bras', amount: 0 },
      { id: 18, name: 't-shirt', amount: 0 },
      { id: 19, name: 'pants', amount: 0 },
      { id: 20, name: 'socks', amount: 0 },
      { id: 21, name: 'underwear', amount: 0 },
      { id: 22, name: 'undershirts/bras', amount: 0 },
      { id: 23, name: 't-shirt', amount: 0 },
      { id: 24, name: 'pants', amount: 0 },
      { id: 25, name: 'socks', amount: 0 },
      { id: 26, name: 'underwear', amount: 0 },
      { id: 27, name: 'undershirts/bras', amount: 0 },
      { id: 28, name: 't-shirt', amount: 0 },
      { id: 29, name: 'pants', amount: 0 },
    ],
  },
  {
    id: 2,
    category: 'Toiletries/hygiene',
    items: [
      { id: 10, name: 'socks', amount: 0 },
      { id: 11, name: 'underwear', amount: 0 },
      { id: 12, name: 'undershirts/bras', amount: 0 },
      { id: 13, name: 't-shirt', amount: 0 },
      { id: 14, name: 'pants', amount: 0 },
      { id: 15, name: 'socks', amount: 0 },
      { id: 16, name: 'underwear', amount: 0 },
      { id: 17, name: 'undershirts/bras', amount: 0 },
      { id: 18, name: 't-shirt', amount: 0 },
      { id: 19, name: 'pants', amount: 0 },
      { id: 20, name: 'socks', amount: 0 },
      { id: 21, name: 'underwear', amount: 0 },
      { id: 22, name: 'undershirts/bras', amount: 0 },
      { id: 23, name: 't-shirt', amount: 0 },
      { id: 24, name: 'pants', amount: 0 },
      { id: 25, name: 'socks', amount: 0 },
      { id: 26, name: 'underwear', amount: 0 },
      { id: 27, name: 'undershirts/bras', amount: 0 },
      { id: 28, name: 't-shirt', amount: 0 },
      { id: 29, name: 'pants', amount: 0 },
    ],
  },
  {
    id: 3,
    category: 'Travel essentials',
    items: [
      { id: 10, name: 'socks', amount: 0 },
      { id: 11, name: 'underwear', amount: 0 },
      { id: 12, name: 'undershirts/bras', amount: 0 },
      { id: 13, name: 't-shirt', amount: 0 },
      { id: 14, name: 'pants', amount: 0 },
      { id: 15, name: 'socks', amount: 0 },
      { id: 16, name: 'underwear', amount: 0 },
      { id: 17, name: 'undershirts/bras', amount: 0 },
      { id: 18, name: 't-shirt', amount: 0 },
      { id: 19, name: 'pants', amount: 0 },
      { id: 20, name: 'socks', amount: 0 },
      { id: 21, name: 'underwear', amount: 0 },
      { id: 22, name: 'undershirts/bras', amount: 0 },
      { id: 23, name: 't-shirt', amount: 0 },
      { id: 24, name: 'pants', amount: 0 },
      { id: 25, name: 'socks', amount: 0 },
      { id: 26, name: 'underwear', amount: 0 },
      { id: 27, name: 'undershirts/bras', amount: 0 },
      { id: 28, name: 't-shirt', amount: 0 },
      { id: 29, name: 'pants', amount: 0 },
    ],
  },
  {
    id: 4,
    category: 'Other',
    items: [
      { id: 10, name: 'socks', amount: 0 },
      { id: 11, name: 'underwear', amount: 0 },
      { id: 12, name: 'undershirts/bras', amount: 0 },
      { id: 13, name: 't-shirt', amount: 0 },
      { id: 14, name: 'pants', amount: 0 },
      { id: 15, name: 'socks', amount: 0 },
      { id: 16, name: 'underwear', amount: 0 },
      { id: 17, name: 'undershirts/bras', amount: 0 },
      { id: 18, name: 't-shirt', amount: 0 },
      { id: 19, name: 'pants', amount: 0 },
      { id: 20, name: 'socks', amount: 0 },
      { id: 21, name: 'underwear', amount: 0 },
      { id: 22, name: 'undershirts/bras', amount: 0 },
      { id: 23, name: 't-shirt', amount: 0 },
      { id: 24, name: 'pants', amount: 0 },
      { id: 25, name: 'socks', amount: 0 },
      { id: 26, name: 'underwear', amount: 0 },
      { id: 27, name: 'undershirts/bras', amount: 0 },
      { id: 28, name: 't-shirt', amount: 0 },
      { id: 29, name: 'pants', amount: 0 },
    ],
  },
];
