export const LOAD_DATA = 'LOAD_DATA';
export const DELETE_ITEM = 'DELETE_ITEM';
export const CHANGE_ITEM_AMOUNT = 'CHANGE_ITEM_AMOUNT';
export const CREATE_PACKING_LIST = 'CREATE_PACKING_LIST';
export const REMOVE_PACKING_LIST = 'REMOVE_PACKING_LIST';
